Repository parity-js/shell, pull requests merged in 2018-04, with the labels that each got.

#44 Nice readme for Parity UI
  README.md
Labels: A8-looksgood, F5-documentation, P2-asap

#45 Add readme
  README.md
Labels: A0-pleasereview, A2-insubstantial, F5-documentation

#46 Fix --ws-port and --ws-interface
  package-lock.json
  package.json
  src/Connection/connection.js
  src/index.electron.js
  src/index.parity.js
  src/secureApi.js
Labels: A8-looksgood

#52 Prefill new issue - next
  .github/ISSUE_TEMPLATE.md
Labels: A8-looksgood

#55 Remove console errors due to service worker
  package-lock.json
  package.json
  src/serviceWorker.js
  webpack/app.js
Labels: A0-pleasereview

#76 Reorganize files
  .gitlab-ci.yml
  electron/config.json
  electron/index.js
  electron/installers/windows/windowInstaller.nsh
  electron/menu/index.js
  electron/util/parityInstallLocation.js
  electron/util/promiseAny.js
  package-lock.json
  package.json
  scripts/publish-snap.sh
  src/Dapp/dapp.js
  webpack/app.js
  webpack/electron.js
Labels: A8-looksgood

#79 Auto-Fetch parity on first run
  electron/cli/index.js
  electron/config.json
  electron/fetchParity/index.js
  electron/index.js
  electron/messages/index.js
  electron/messages/runParity.js
  electron/messages/signerNewToken.js
  electron/util/parityInstallLocation.js
  electron/util/parityPath.js
  electron/util/promiseAny.js
  package-lock.json
  package.json
  src/Connection/connection.js
  webpack/electron.js
Labels: A8-looksgood
