Repository parity-js/shell, pull requests merged in 2018-06, with the labels that each got.

#126 Add dapp-wallet to built-in dapps; load it from fs
  package-lock.json
  package.json
  src/Dapps/dappsBuiltin.json
  src/Dapps/store.js
  src/inject.js
Labels: A8-looksgood

#137 Fix eaccess bug in electron
  electron/operations/signerNewToken.js
  package-lock.json
Labels: A8-looksgood

#138 Remove preload.js path verification
  electron/index.js
Labels: A8-looksgood, B0-patchthis

#139 [Beta] Remove preload.js path verification
  electron/index.js
  package-lock.json
  package.json
Labels: A8-backport

#140 [stable] Remove preload.js path verification
  package-lock.json
  package.json
  src/index.electron.js
Labels: A8-backport
