Repository parity-js/shell, pull requests merged in 2018-05, with the labels that each got.

#82 Fix opening external links
  electron/index.js
  package-lock.json
  package.json
  src/Dapp/dapp.js
  webpack/electron.js
Labels: A8-looksgood

#93 Rerun CI
  scripts/test.js
Labels: A2-insubstantial

#89 [BETA] Update readme and gitlab on beta
  .gitlab-ci.yml
  README.md
  scripts/publish-snap.sh
  scripts/push-precompiled.sh
Labels: A8-backport, A8-looksgood

#87 [STABLE] Update gitlab & readme on stable branch
  .gitlab-ci.yml
  README.md
  scripts/publish-snap.sh
  scripts/push-precompiled.sh
Labels: A8-backport, A8-looksgood

#107 Use commander instead of yargs for CLI
  electron/cli/helpMessage.js
  electron/cli/index.js
  electron/index.js
  electron/operations/runParity.js
  package-lock.json
  package.json
Labels: A8-looksgood, B0-patchthis

#108 [BETA] Use commander instead of yargs
  electron/cli/helpMessage.js
  electron/cli/index.js
  electron/index.js
  electron/operations/runParity.js
  package-lock.json
  package.json
Labels: A8-backport, A8-looksgood

#99 Fix appId heuristics in inject.js
  src/inject.js
Labels: A8-looksgood

#109 Fix small bug in CLI
  electron/cli/index.js
Labels: A8-looksgood, B0-patchthis

#110 [BETA] Fix small bug CLI
  electron/cli/index.js
  package-lock.json
  package.json
Labels: A8-backport, A8-looksgood

#114 Move Dapps files from @parity/shared ; display icons of builtin dapps from filesystem
  package-lock.json
  package.json
  src/Dapp/dapp.js
  src/DappRequests/RequestGroups/RequestGroups.js
  src/Dapps/dapps.js
  src/Dapps/dappsBuiltin.json
  src/Dapps/store.js
  src/Dapps/store.spec.js
  src/ParityBar/parityBar.js
  src/shellMiddleware.js
  src/util/dapps.js
  src/util/host.js
  webpack/app.js
Labels: A8-looksgood

#120 Update plugin signer account
  package-lock.json
  package.json
Labels: A9-FUCKYEAH!1

#121 Update to electron 2
  package-lock.json
  package.json
  src/Dapp/dapp.js
Labels: A8-looksgood, B0-patchthis, F1-security

#122 [Beta] Update electron
  package-lock.json
  package.json
  src/Dapp/dapp.js
Labels: A8-backport

#123 [STABLE] Update Electron
  package-lock.json
  package.json
  src/Dapp/dapp.js
Labels: A8-backport
