Repository parity-js/shell, pull requests merged in 2018-07, with the labels that each got.

#146 Restrict in-frame navigation for dapps
  electron/index.js
Labels: A8-looksgood

#152 Fix bug uglifyjs
  package-lock.json
  package.json
  webpack/shared.js
Labels: A0-pleasereview

#144 Download network dapps and load them from filesystem
  .gitignore
  Cargo.precompiled.toml
  Cargo.toml
  build.rs
  electron/index.js
  electron/operations/runParity.js
  package-lock.json
  package.json
  scripts/build.sh
  src/Connection/connection.js
  src/Dapp/dapp.css
  src/Dapp/dapp.js
  src/DappRequests/methodGroups.js
  src/Dapps/store.js
  src/index.parity.js
  src/inject.js
  src/lib.rs
  src/lib.rs.in
  src/secureApi.js
  src/util/dapps.js
  src/util/hashFetch/expoRetry.js
  src/util/hashFetch/index.js
  src/util/host.js
  wasm/README.md
  wasm/ethkey/.gitignore
  wasm/ethkey/Cargo.toml
  wasm/ethkey/base64ify.js
  wasm/ethkey/build.sh
  wasm/ethkey/ethkey.opt.wasm
  wasm/ethkey/ethkey.wasm
  wasm/ethkey/src/main.rs
  webpack/app.js
  webpack/shared.js
Labels: A8-looksgood

#158 Disable GPU on linux (fix #157)
  electron/index.js
Labels: A0-pleasereview

#156 Restrict dapp access to resources
  electron/index.js
Labels: A0-pleasereview

#164 Fix network dapp icons not displaying in dapp-dapp-visible
  electron/index.js
Labels: A8-looksgood

#163 [BETA] Only allow Parity 1.10 and 1.11
  src/Connection/connection.js
Labels: A8-looksgood

#162 Update packages
  package-lock.json
  package.json
  src/SyncWarning/syncWarning.spec.js
Labels: A8-looksgood

#169 [BETA] Bump 0.3 to beta
  package.json
  scripts/publish-snap.sh
Labels: A8-looksgood

#170 Update master to 0.4
  package-lock.json
  package.json
  scripts/publish-snap.sh
Labels: A8-looksgood

#173 Fix fetchParity(mainWindow) race condition
  electron/index.js
  src/util/dapps.js
Labels: A8-looksgood, B0-patchthis

#174 [beta] backport: Fix fetchParity(mainWindow) race condition (#173)
  electron/index.js
  src/util/dapps.js
Labels: A8-backport, A8-looksgood

#176 Bump to 0.3.2
  package-lock.json
  package.json
Labels: A0-pleasereview

#175 Parity UI is not actively maintained anymore
  README.md
Labels: A8-looksgood
