Repository parity-js/shell, pull requests merged in 2018-08, with the labels that each got.

#177 Use persistent storage
  .gitlab-ci.yml
  electron/index.js
  package-lock.json
  package.json
  src/Dapp/dapp.js
  src/DappRequests/store.js
  src/inject.js
  src/preload.js
  src/shellMiddleware.js
Labels: A8-looksgood, B0-patchthis

#186 [BETA] Use persistent storage
  .gitlab-ci.yml
  electron/index.js
  package-lock.json
  package.json
  src/Dapp/dapp.js
  src/DappRequests/store.js
  src/inject.js
  src/preload.js
  src/shellMiddleware.js
Labels: A8-backport

#187 Remove`getLocalDappsPath` as not used
  electron/index.js
  electron/utils/paths.js
Labels: A8-looksgood

#190 [BETA] Update electron-builder
  package-lock.json
  package.json
Labels: A0-pleasereview

#191 Update to latest electron-builder
  package-lock.json
  package.json
Labels: A0-pleasereview

#200 Update electron and electron-builder
  package-lock.json
  package.json
Labels: A8-looksgood
